module.exports = {
  apps: [
    {
      name: "ta-frontend-main",
      script: "npm",
      args: "run start",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      wait_ready: false,
      listen_timeout: 15000,
      kill_timeout: 8000,
      env: {
        // NODE_ENV: 'production',
        // PORT: 3000,
        // NEXT_PUBLIC_GRAPHQL_API: process.env.NEXT_PUBLIC_GRAPHQL_API,
        // FRONTEND_URL: process.env.FRONTEND_URL,
        // MINIO_ENDPOINT: process.env.MINIO_ENDPOINT,
        // MINIO_SSL: process.env.MINIO_SSL,
        // MINIO_PORT: process.env.MINIO_PORT,
        // MINIO_ACCESS_KEY: process.env.MINIO_ACCESS_KEY,
        // MINIO_SECRET_KEY: process.env.MINIO_SECRET_KEY,
        // MINIO_BUCKET_NAME: process.env.MINIO_BUCKET_NAME
      },
    },
    {
      name: "ta-frontend-secondary",
      script: "npm",
      args: "run start:pm2",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      wait_ready: false,
      listen_timeout: 15000,
      kill_timeout: 8000,
      env: {
        // NODE_ENV: 'production',
        // PORT: 3001,
        // NEXT_PUBLIC_GRAPHQL_API: process.env.NEXT_PUBLIC_GRAPHQL_API,
        // FRONTEND_URL: process.env.FRONTEND_URL,
        // MINIO_ENDPOINT: process.env.MINIO_ENDPOINT,
        // MINIO_SSL: process.env.MINIO_SSL,
        // MINIO_PORT: process.env.MINIO_PORT,
        // MINIO_ACCESS_KEY: process.env.MINIO_ACCESS_KEY,
        // MINIO_SECRET_KEY: process.env.MINIO_SECRET_KEY,
        // MINIO_BUCKET_NAME: process.env.MINIO_BUCKET_NAME
      },
    },
  ],
};
